name: Ruff

on:
  push:
    branches:
      - dev
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - dev
    paths:
      - "**/*.py"

env:
  WORKING_DIRECTORY: "."
  RUFF_OUTPUT_FILENAME: "ruff.log"
  CUSTOM_FLAGS: ""

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Environment setup
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11

      # - name: Install dev dependencies
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip install ruff

      - name: Ruff as GitHub actions
        uses: astral-sh/ruff-action@v1